# See https://reuse.software/spec-3.3/#reusetoml for specification
version = 1

[[annotations]]
path = [
    ".gitignore",
    "README.md",
    "REUSE.toml",
    ".github/**"
]
SPDX-FileCopyrightText = "Deutsche Telekom AG"
SPDX-License-Identifier = "CC0-1.0"
