# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>, Deutsche Telekom AG

name: REUSE Compliance Check

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

  schedule:
    # Weekly on Saturdays at 1:30AM
    - cron: '30 1 * * 6'

# Set default permission for all jobs to none
permissions: {}

jobs:
  test-reuse-compliance:
    runs-on: ubuntu-22.04
    
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: "Run REUSE Compliance Check"
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5.0.0
